#Importing the libraries

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset

In [40]:
# Read the csv contatining data
dataset = pd.read_csv('/content/Data.csv') 
X = dataset.iloc[:,1:-1].values # Getting Feature columns
y = dataset.iloc[:,-1].values # getting last column
X.shape, y.shape #printing the shape

((683, 9), (683,))

# Splitting Dataset into Train and Test set

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,
                                                    random_state=0)

# Feature Scaling

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [43]:
X_train_scaled[:10]

array([[ 0.91903747,  0.9407658 ,  2.30881719,  0.77265864, -0.10307335,
         1.80910082,  2.22576767,  2.27129602,  0.24623928],
       [ 1.27578287, -0.04290763,  1.63138773,  0.06811505,  0.3404019 ,
         1.53244024,  1.82407819,  1.94996317,  3.74830911],
       [ 1.27578287,  2.25233038,  2.30881719,  2.53401762,  1.22735239,
         1.80910082,  2.62745714,  2.27129602, -0.33743902],
       [-1.22143494, -0.69868992, -0.73961536, -0.63642854, -0.5465486 ,
        -0.68084439, -0.98774815, -0.62069958, -0.33743902],
       [-1.22143494, -0.69868992, -0.06218591, -0.63642854, -0.99002384,
        -0.68084439, -0.58605867, -0.62069958, -0.33743902],
       [-1.22143494, -0.69868992, -0.73961536, -0.63642854, -0.5465486 ,
        -0.68084439, -0.98774815, -0.62069958, -0.33743902],
       [ 0.20554667,  0.9407658 ,  0.95395828, -0.28415674,  0.3404019 ,
         1.80910082, -0.18436919,  0.98596464, -0.33743902],
       [-0.50794414, -0.69868992, -0.73961536, -0.63642854, -0

In [44]:
y_train[:10]

array([4, 4, 4, 2, 2, 2, 4, 2, 2, 4])

# Training All Classification Model

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [46]:
lrclf = LogisticRegression()
knnclf = KNeighborsClassifier()
svclinclf = SVC(kernel='linear')
svckrnclf = SVC(kernel='rbf')
nbclf = GaussianNB()
cartclf = DecisionTreeClassifier()
rfclf = RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)

In [47]:
classifiers = [lrclf,knnclf,svclinclf, svckrnclf, nbclf, cartclf, rfclf]
names = ['Logistic Regression', 
         'KNN',
         'Support vector machine',
         'SVM kernalized'
         'Naive Bayes',
         'Decision Tree',
         'Random Forest']

In [48]:
def classify(clf, Classifier_Name):
    print('='*100)
    print()
    print(Classifier_Name + '\n')
    clf.fit(X_train_scaled, y_train)
    y_hat = clf.predict(X_test_scaled)
    from sklearn.metrics import confusion_matrix
    print(confusion_matrix(y_test, y_hat))
    from sklearn.metrics import accuracy_score
    print(f'\nAccuracy: {accuracy_score(y_test, y_hat) * 100}%')

In [49]:
for clf, name in zip(classifiers, names):
    classify(clf, name)


Logistic Regression

[[103   4]
 [  5  59]]

Accuracy: 94.73684210526315%

KNN

[[103   4]
 [  5  59]]

Accuracy: 94.73684210526315%

Support vector machine

[[102   5]
 [  5  59]]

Accuracy: 94.15204678362574%

SVM kernalizedNaive Bayes

[[101   6]
 [  3  61]]

Accuracy: 94.73684210526315%

Decision Tree

[[99  8]
 [ 2 62]]

Accuracy: 94.15204678362574%

Random Forest

[[105   2]
 [  6  58]]

Accuracy: 95.32163742690058%
